### ISSUE TITLE
Entity and migrations for hashtags schema

### ISSUE THREAD

**Issue by ritvij14** [Devsoc-BPGC/bits-stack-backend#15]
**Is your feature request related to a problem? Please describe.**

We need an entity for hashtags schema
![image](https://user-images.githubusercontent.com/51456744/111881438-5bbc3600-89d6-11eb-8efc-4bea6169ce33.png)

**Describe the solution you'd like**

Create an entity and generate migrations for hashtags schema

**Comment by Devesh21700Kumar** [comment]
/* eslint-disable @typescript-eslint/no-unused-vars */
import {
	Entity,
	PrimaryGeneratedColumn,
	Column
} from 'typeorm';


@Entity({name: 'Tags'})
export class Tags {

	@PrimaryGeneratedColumn({ type:'int'})
	Tag_ID?: Number;

	@Column({ type: 'varchar', unique: true})
	Tag_Name!: string;

}

**Comment by Devesh21700Kumar** [comment]
> /* eslint-disable @typescript-eslint/no-unused-vars */
> import {
> Entity,
> PrimaryGeneratedColumn,
> Column
> } from 'typeorm';
> 
> @entity({name: 'Tags'})
> export class Tags {
> 
> ```
> @PrimaryGeneratedColumn({ type:'int'})
> Tag_ID?: Number;
> 
> @Column({ type: 'varchar', unique: true})
> Tag_Name!: string;
> ```
> 
> }

@ritvij14
