### ISSUE TITLE
Addition of Entity for channel  announcements 

### ISSUE THREAD

**Issue by resonantChaos22** [Devsoc-BPGC/bits-stack-backend#7]
**Is your feature request related to a problem? Please describe.**
It's a feature request for announcements,  channel discussions and questions.

**Describe the solution you'd like**
An entity ChannelDiscussions through which we are able to store data related to channel discussions, announcements and questions. It should be made according to the ER diagram.

**Comment by Devesh21700Kumar** [comment]
Taking this Up
